### ISSUE TITLE
Live session enhancements

### ISSUE THREAD

**Issue by sursaone** [vurilo/roadmap#105]
As an admin of a live session, I want following

1.  Recordings and assignments should be available on the session management page
<img width="524" alt="image" src="https://user-images.githubusercontent.com/37689201/209937161-122fcb3a-d075-468e-be49-c3472274e4c9.png">

* Rename edit to the Details page and just show the detail with the form, there should be a button to click to Edit and save the changes
* Move the sections and lessons management from the course detail to the recordings menu
* Move the assignments management to the live session itself.
3.  Enhance the participant page with below

- [ ] Should be able to add/edit/remove/inactivate users
- [ ] Should be able to view the last class joined date with the total duration for that day 
- [ ] Should be able to categorize the user with `Interested`, 'Paid', 'Ideal`, 'Inactive', 'Partial Paid', 'Demo'
- [ ] If any user joins as a demo, he should be listed here with "Demo (xxx)" label where xxx is the count of demos taken
- [ ] Add an option to bulk import user's with status 
- [ ] Instead of infinite scrolling, please use number pagination with the option to change the page size.

5.  Add a new section called "Sales & Opportunity", it will be mini CRM
- [ ] Track the user who has visited my live class and show the stats on a daily basis so I can call them or contact them
- [ ] If any user comes without login just track the counts of visits.
- [ ] SHould capture from where the user came through
- [ ] Should capture the Device he is using 
- [ ] Provide an option to import the leads from excel and add them manually
- [ ] SHould be able to convert the user to the participant 
- [ ] Should be able to add any notes
- [ ] Should be able to send SMS or email from the app to the particular user

6. Add a new section called "Messaging"

- [ ] should be able to send email/sms/push/in-app notifications to my participants or all or selected users
- [ ] Should be able to view past messages and use that for new message

**Comment by Amir-Khanal** [comment]
https://github.com/vurilo/roadmap/issues/101

**Comment by Amir-Khanal** [comment]
https://github.com/vurilo/roadmap/issues/103

**Comment by Amir-Khanal** [comment]
https://github.com/vurilo/roadmap/issues/96

**Comment by ST-Saurabh** [comment]
- [ ] need to add the individual/bulk enroll from the frontend so that the dependency of our support team and admino will be reduced.

- [ ] need to add in team after enrolling user into event.(if the live session is in team)
