### ISSUE TITLE
Bulk invitation of Members on the basis of roles

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#11]
Admin should be able to invite multiple users to the team at once.

1. A dropdown should be present including roles: Teacher, Member
2. Admin should be allowed to Select Teacher Role and invite team members at bulk
3. Admin should be allowed to Select Member Role and invite team members at bulk

**Comment by Rashi011** [comment]
### These are the steps required for Bulk Invitation

1. Admin should be able to add multiple users in TEAMS at once using CSV file. 
2. The CSV file should include the member's email id. 

While clicking on "Invite Members", a pop-up form appears where the "Add email address" field and Import CVS file field can be seen.
![Add Member Pop Up](https://user-images.githubusercontent.com/87527341/159216470-638456de-5c31-4b37-a162-05e37e91bcdc.png)


- In the "Add Email Address" field, the admin should be able to invite up to 10 members only in the first attempt. After the 10th attempt, a validation message should be shown which says "You cannot add more than 10 entries at this moment " 
- In the "Import CVS file" field admin should be able to add CSV to browse or drag and drop the CSV file. The CSV file should include the email address of the members who have already signed up for the application. 
- Need to filter out signed-up members from the CSV file and teachers should be notified about the invitation sent to the members in the CSV which can be included in the pending invitation section with labels, "Registered User" and "Unregistered User"
![Pending list](https://user-images.githubusercontent.com/87527341/159216502-d2c79ad3-fd03-4395-9ea1-a8621eebb8a0.png)

**Comment by ST-Saurabh** [comment]
We have different workflow for now so closing
