### ISSUE TITLE
Assignment

### ISSUE THREAD

**Issue by saurabhchaulagai** [vurilo/roadmap#14]
Teacher should be able to create assignment.
Student should be able to submit assignment.

**Comment by saurabhchaulagai** [comment]
### TEACHER PERSPECTIVE
1. Login to uat.vurilo.com.
2. click on the profile icon from the top right corner.
3. Select teach from the option. Filling the pop up form will create a course. After submitting the form it will redirect to course detail page.
![image](https://user-images.githubusercontent.com/70097566/150075394-36848e00-cd27-44a6-85f7-91395fa51661.png)

**Page Now**
![new requirement of assignment](https://user-images.githubusercontent.com/70097566/150075593-f3dc27bc-2e98-4529-8df5-8d0df0709a98.png)

**Page Then**
4. Here teacher should be able to create assignment from the assignment section for the course. and should able to track all the assignment from this section. Teacher should be able to give assignment in the basis of lesson and section also. The assignment for the section should be created from add new assignment button which will be side by the add new lesson button. and for the lesson assignment the teacher should be able to add the assignment from the new button add new assignment which will be side by add attachment. Teacher should be able to track all the assignment of the enrolled student from the assignment tab.
### STUDENT PERSPECTIVE
1.  Login to uat.vurilo.com.
2. click on the course u want to enroll or u have enrolled and want to submit the assignment.
3. the lesson based assignment will be shown to the student while he is in the individual lesson and should be able to submit the assignment and take the assignment from here.
![new requirement of assignment1](https://user-images.githubusercontent.com/70097566/150077001-9ac92c18-3a2c-4584-9415-2a4de0b5be01.png)
**How student will see in the lesson perspective**
4. The section based assignment will be shown in the lesson listing field at the button of the lesson in every section and should be able to submit the assignment and take the assignment from here..
5. The course based assignment will be shown in the section and lesson listing field at the button of the all section and lesson in every course and should be able to submit the assignment and take the assignment from here.
6. The student should be able to track their assignment from the my learning tab. the assignment should be categorized in submitted assignment, not submitted assignment and should be able to submit the assignment from here also.

**Comment by Rashi011** [comment]
https://docs.google.com/document/d/1B4G-BGKM7DZgyk_8DFS2ZYXYADKBExWRSioq9O18GUE/edit?usp=sharing 
Link to the requirements for assignment by @saurabhchaulagai

**Comment by Rashi011** [comment]
Link to the Assignment Requirement Upgrade,

https://github.com/vurilo/stend/issues/632
