### ISSUE TITLE
Sign Up/sign in; using phone Number

### ISSUE THREAD

**Issue by Amir-Khanal** [vurilo/roadmap#17]
**Description:**
User should be able to Sign up into VURILO using phone number(mobile number).

**Comment by Rashi011** [comment]
**Log In**

1. Users should be able to log in through email as well as phone number 
2. User will enter the password and click the login button

**Sign Up** 

1. Sign up with the email tab

- > Our existing Sign-Up process 

![sign up](https://user-images.githubusercontent.com/87527341/167825736-45e4e7f1-bf30-463b-a9b5-74e12cd6fc21.png)
Or,
![image](https://user-images.githubusercontent.com/87527341/167826624-33439c4e-3a8b-467d-9f11-f8d4c622856b.png)


2. Sign Up with the phone number tab [For new users]

- > Users should be able to enter their phone number and continue
- > After clicking on the "Continue" button, there must be a field to enter OTP that was sent to their number via SMS
- > After clicking on the "Submit" button, a new page should open where users must fill in some details, which contains fields like:

- New Password
- Confirm Password
- First Name 
- Last Name
- Email address

**Conditions**

1. If users sign up through a phone number and fill in the details along with their email but do not verify their email, they will have to continue as unverified users with all the restrictions. 
![image](https://user-images.githubusercontent.com/87527341/167828021-066b6439-dce4-422a-9dd6-add448ea5552.png)

**Comment by Rashi011** [comment]
Requirement 2: 
**Log In**

1. Users should be able to log in through email as well as phone number 
2. User will enter the password and click the login button

**Sign Up** 

1. Sign up with the email tab

- > Our existing Sign-Up process 

2. Sign Up with the phone number tab [For new users]

- > Users should be able to enter their phone number and continue
- > After clicking on the "Continue" button, there must be a field to enter OTP that was sent to their number via SMS
- > After clicking on the "Submit" button, a new page should open where users must fill in some details, which contains fields like:

- First Name (required)
- Last Name (required)
- Email address

**Users who have signed up via phone number should have permission equal to the verified users. Permission to the users who have signed up via phone number**

1. Admin or authors should be able to add members by their phone number 
2. Users who have signed up via phone numbers should be able to join live sessions
3. Users should be able to join Team Meeting/Public Live meeting
4. Users should be able to enroll in the courses
5. Users should be able to create a course 
6. Users should be able to create a live session

**Setting page**

1. Edit Profile: should have fields to upload a profile picture, first name(required), last name(required), email, profession, phone number(required) Website URL, Bio, Facebook URL, Twitter URL, Youtube URL, GitHub Url, Instagram URL, and LinkedIn URL

Note: 
![image](https://user-images.githubusercontent.com/87527341/168548791-565ef0fd-631e-42bf-a742-ae2efd51c6d9.png)

2. Change Phone Number: There should be a **Change Phone Number** option with fields like; Current Phone Number, New Phone Number
Ref:
![image](https://user-images.githubusercontent.com/87527341/168550153-9c669268-bfd6-4d3b-8107-a5274523424a.png)

Note: On updating phone number, users should again be asked for an OTP/confirmation code which will be sent to their updated phone number.
