### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#18]
The landing page will replace the current home page. 
Link to the design, 
[https://www.figma.com/proto/A04JfDz5KzU7Ol7tOW0HnW/FINAL-VURILO-NEPAL-LANDING-PAGE?node-id=2%3A102&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=2%3A102](url)

**Comment by Amir-Khanal** [comment]
https://github.com/vurilo/stend/issues/549
