### ISSUE TITLE
Configurable course for teachers

### ISSUE THREAD

**Issue by sursaone** [vurilo/roadmap#21]
different teacher per lesson on the same course

**Comment by Amir-Khanal** [comment]
A course can contain multiple lessons; each lessons can be taught by different teacher.
There needs to be dropdown to select the teaceher.

**Comment by Rashi011** [comment]
@sursaone could you please provide us with more details regarding this ticket?

**Comment by Amir-Khanal** [comment]
https://github.com/vurilo/stend/issues/1284
