### ISSUE TITLE
language support with link in url

### ISSUE THREAD

**Issue by Amir-Khanal** [vurilo/roadmap#23]
User should be able to share the url of the page selecting the language.
The same page should be viewed as the language that was previously shared.
![image](https://user-images.githubusercontent.com/98070324/154649552-5a2dee73-5bf3-40a7-95c2-9ece163602e8.png)

![image](https://user-images.githubusercontent.com/98070324/154649641-758a159c-8d7b-4be7-ac9f-37264492927e.png)

**Comment by Rashi011** [comment]
@Amir-Khanal what is the status of this ticket? please check and confirm

**Comment by Amir-Khanal** [comment]
This task is completed. Now we can include /ne in url to be shared among the users. The user will get current language state when it has been shared

e.g: https://uat.vurilo.com/ne/teach for nepali page
https://uat.vurilo.com/en/teach for english page
