### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#34]
Contact details should be placed in the top header and footer.

**Comment by Rashi011** [comment]
**Reference**

**1. In the top header**
![1](https://user-images.githubusercontent.com/87527341/163527534-a1031ad9-2270-4145-8e4e-76fd42798b04.png)


**2. In the footer**
![यातायात व्यवस्था विभाग - Google Chrome 2022-04-15 ](https://user-images.githubusercontent.com/87527341/163527465-2a6057b1-620e-4037-b7fd-15d9f4b26e9b.png)

**Comment by phuyalrn22** [comment]
Color of header?

**Comment by subhamsursa** [comment]
@alinac7 please help with design

**Comment by subhamsursa** [comment]
> For now, the contact details will be only in the header section.
> 
> * Design Sample
>   ![image](https://user-images.githubusercontent.com/96462002/165934229-c4d66d2c-ce19-4bd4-86a7-388fbb3110ee.png)
> * Banner CSS Code:
>   position: absolute;
>   width: 1440px;
>   height: 64px;
>   left: 0px;
>   top: 0px;
>   background: linear-gradient(90deg, #10DDC2 0%, #123646 53.12%, #10DDC2 100%);
> * Link to design file: https://www.figma.com/file/yoeFGwB3LsOZDi545yCgbM/Vurilo-Web?node-id=2585%3A15567

@alinac7 is this approved design for development.

cc: @sursaone @Rashi011

**Comment by Rashi011** [comment]
@alinac7 we need footer as well 

![image](https://user-images.githubusercontent.com/87527341/166185474-9820311d-9d25-4d96-af69-f0bf453c4002.png)

**Comment by alinac7** [comment]
### Updated contact us design
![image](https://user-images.githubusercontent.com/96462002/166215913-88fa07be-fa7b-40ed-8da8-f677c53069af.png)

**Comment by sursaone** [comment]
@alinac7 @subhamsursa  @Rashi011  looks good for me

**Comment by subhamsursa** [comment]
okay starting development for this ticket. 
@phuyalrn22 please check this

**Comment by Rashi011** [comment]
We are not including the header banner after log in but we need to display it in landing page when the user is not logged in
