### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#37]
Users should be able to delete their account

**Comment by Rashi011** [comment]
**To Do**

1. On deleting the account, users should not be able to restore their old account information like

- users' personal information on the profile should be removed
- the course that has been created by the user should be removed from Vurilo
- user should be removed from the team 
- all the enrolled courses should be gone
- every data should be deleted for that user

2. To use Vurilo again, users need to create a new account.

**Comment by Rashi011** [comment]
@Amir-Khanal please go through this so that we can pick this ticket for development

**Comment by Rashi011** [comment]
reference:

[ttps://support.udemy.com/hc/en-us/articles/229233547-How-to-Close-an-Instructor-Account](https://support.udemy.com/hc/en-us/articles/229233547-How-to-Close-an-Instructor-Account)

**Comment by sursaone** [comment]
@Rashi011 @Amir-Khanal, we need this one before releasing the iOS app. Everything to release the iOS app is ready from our side.

**Comment by Rashi011** [comment]
Okay sir 
@sursaone
