### ISSUE TITLE
Sign Up - Disable Email Verification 

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#38]
### **Description**

Need to remove email verification during user sign-up. 

1. Users should be able to join live sessions but not CREATE LIVE SESSIONS.
2. Users should be able to join Team Meeting/Public Live meeting but not CREATE TEAM/Create Team meeting (although the role is changed to admin or teacher) and LIVE MEETING.
3. Users should be able to enroll in the courses but not CREATE COURSES. 

4.  There should be a notice/message banner above the navigation bar saying "A confirmation email was sent to xyz@gmail.com. Please confirm this email address. "
For reference:
![image (21) png ‎- Photos 2022-03-29 15 43 06](https://user-images.githubusercontent.com/87527341/160586244-520c94cd-1faf-4b2f-b8ed-34c86a5b21c3.png)

**Comment by sursasagar** [comment]
Number 1 , 2 , 3 are implemented by backend
Number 4  is frontend implementation

**Comment by Rashi011** [comment]
@phuyalrn22, please look into it

**Comment by phuyalrn22** [comment]
@Amir-Khanal what we need to change on this

**Comment by phuyalrn22** [comment]
@bipulmgr done from my side

**Comment by Rashi011** [comment]
To-Dos from backend dev:

disable create a meeting in the team and public.
disable create team
disable edit team
disable create subteam
disable edit subteam
disable delete subteams
disable delete meeting
disable courses
disable edit courses
disable create a live session
