### ISSUE TITLE
Assessment Feature : MCQ 

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#39]
Teachers should be able to prepare an online test and share it with the students and analyze the result

**Comment by Rashi011** [comment]
**FEATURES:**

1. Test/Assessment Feature MCQ (Multiple Choice Question)
2. Question Bank
3. Standardized Test System with the mock environment (e.g. IELTS, PTE, GRE, ….)


## FEATURE #1. Test/Assessment Feature MCQ
**As an AUTHOR/Teacher or Creator**

1. Teacher/Author should be able to create assessment/test MCQ
2. Created assessment can be mapped with courses
3. Teacher/Author can also create independent tests/assessment

![MCQ - Assessment - Google Docs - Google Chrome 202](https://user-images.githubusercontent.com/87527341/163126988-8e9cce00-d5a4-49f0-a34b-f6ec737d0bf2.png)


Question Pool:
This option will ensure the question re-usability in multiple test sets

1. The teacher/Author should be able to create questions
2. Teacher/Author should be able to view created Questions
3. Teacher/Author should be able to Edit Questions
4. Teacher/Author should be able to Delete Questions

**Create Questions forms required information**

1. Question title ( to be displayed as a question) - Mandatory
2. Question ( text editor field to be displayed as a question ) - Optional
3. Images Attachments (to be displayed as a question) - Optional
4. Answer Choices Options - Mandatory
5. Correct Answer Check box (in every Answer Choice) - Mandatory(at least one)
6. Question Weightage - Optional
7. Question Type (image question, text question, audio question) - Optional (can be taken as enhancement)
8. Question Category - Mandatory (Categories from the backend/Create one)
9. Question Difficulty level - mandatory

**Advantages Of Question**

1. Questions can be reusable
2. Random Question Sets can be created


Test Set Pool:
![MCQ - Assessment - Google Docs - Google Chrome 202](https://user-images.githubusercontent.com/87527341/163126851-b830a98c-1671-467f-a20c-fd6fd79e0f0c.png)

1. Teacher/Author can create test sets by selecting questions from questions pool
2. Questions can be created during Test set creation; These questions should also be displayed in question pool
3. Test set can be Time-based or Time-free
4. Test set can be public or team 
5. Test set can be paid or free
6. Questions can be selected in completely random manner
7. Related courses can also be selected to Test Set

### Create a Test set form

1. Test title - Mandatory
2. Thumbnail - Optional
3. Test Description - Optional
4. Question Selector - Mandatory
5. Or, Question creator - Optional
6. Test Time - Optional
7. Test scope Team/ Public - Mandatory
8. Test Price - Mandatory
9. Related Courses - Optional

**Comment by Rashi011** [comment]
**Before Sign-Up/Log-In**
1. User should be able to view the "Assessment" button on the landing page

**After Sign-Up/Log-In**
1. User should be able to view "Assessment" in the Dashboard
2. User should be able to view "Assessment" in the dropdown of the profile icon
3. User should be able to view "Assessment" in the related courses below the assignment menu.
4. User should be able to view "Assessment" in the related Teams below the assignment menu.

**On clicking the "Assessment" menu**

1. Student View
> Dashboard 
> Assessment List

2. Teacher View
> Dashboard
> Assessment List

**Comment by Rashi011** [comment]
**Some changes to be made**

**While creating an assessment:** 

1. In Test Set Pool add "Test Type" 
2. In creating a test form, add "Test Type" with options, MCQ, subjective, and mix.

@alinac7

**Comment by Rashi011** [comment]
### Reference sites for plugins 

1. Quiz Maker
https://wordpress.org/plugins/quiz-maker/#description
https://ays-pro.com/

2. Quiz and Survey Master
https://wordpress.org/plugins/quiz-master-next/
https://quizandsurveymaster.com/docs/

3. Watu Quiz
https://wordpress.org/plugins/watu/

4. HD Quiz
https://wordpress.org/plugins/hd-quiz/

**Comment by subhamsursa** [comment]
@Rashi011 where are we on this  , Is clear requirement is there so that we can  move this to design. so we can pick this in development 
scenarios 
1. Teacher can upload bulk question sets 
2. Teacher can manually create question set and add questions 
3. Student can choose the question set and randomized question from the set 
4. Student can view there progress on the question 
please update finalised document in docx.  Thank you

**Comment by subhamsursa** [comment]
@phuyalrn22 , please check the LOGIN AUTHENTICATION

Firebase Authentication
https://wordpress.org/plugins/firebase-authentication/

**Comment by Rashi011** [comment]
@subhamsursa sir 
point no.3 is quite confusing. Need a short explanation from you

**Comment by Rashi011** [comment]
**For Teacher's view**

- The teacher's View is going to be CMS
- We can create role-based access for CMS in WordPress which will act as a teacher view
- Teacher should be able to view the list of students who took the test
- Can view the result of every student 
- Teacher can create questions and question set

**Student View**
- Student View is going to be the UI itself
- Students should be able to select the test set
- Student should be able to view their result as self-assessment

**Comment by subhamsursa** [comment]
> @subhamsursa sir point no.3 is quite confusing. Need a short explanation from you
@Rashi011 
the test question set should be generated randomly from the Question set , let's say there are 25 sets of question containing 50 question for "A" course then the selecting set should be random from 25 any of the assessment question should be displayed to student .
cc: @deepaksursa correct me if i am wrong here

**Comment by Rashi011** [comment]
**Two scenarios for test sets:**

1. Entrance Exam

- One-time test 
- Link should be destroyed immediately after attending the exam for the first time by the students
- Students should not be able to view results by themselves

2. Self Assessment exam 

- Multiple-time test
- It should be displayed in the student's view
- Result of this test should be displayed in frontend as well as on CMS

**Types of the Test:**
- Paid/Free
- Time-limited/ Time free

**Features to be included**
- Need to use VURILO's Login
- Need to include payment gateway as ESEWA and KHALTI
- Students may be able to take tests multiple times
- all the enrolled tests should be displayed in the Dashboard in the Frontend UI
- Students should be able to view his/her test result history
- Students should be able to search for the test sets
- Students should be able to apply filter 
- All the created questions set should be displayed under the MCQ Test tab
- The answer to each question during the test should be displayed after the test has been completed

**Comment by suresmaharjan-sursatech** [comment]
@subhamsursa 

Firebase Authentication . This is a premium plugin doesn't works.
https://wordpress.org/plugins/firebase-authentication/

**Comment by Amir-Khanal** [comment]
### **Use Case Diagram for Teacher and Student Role:**

![image](https://user-images.githubusercontent.com/98070324/166293184-3b41843b-3dbc-44e2-9970-7c133854801d.png)

### **UI wireframe**
**1. Dashboard**

![image](https://user-images.githubusercontent.com/98070324/166293679-00abbc44-8b27-4d84-aa50-4ca2f9c73329.png)

**2. MCQ Test Page**

![image](https://user-images.githubusercontent.com/98070324/166295148-c0aa39dd-7c77-4ca1-b2dd-2e9b673d80be.png)

**3. MCQ Test Description Page**

![image](https://user-images.githubusercontent.com/98070324/166297278-465d4b05-03ff-40e7-9a05-25475d9584f1.png)


![image](https://user-images.githubusercontent.com/98070324/166297607-4d33cbe9-fa5e-4cf7-871a-a16f1070eb58.png)


**4. Results Page**

![image](https://user-images.githubusercontent.com/98070324/166297866-921364a7-16dc-4822-b59c-37ea8a869a85.png)


![image](https://user-images.githubusercontent.com/98070324/166299855-cde8d71e-0bc9-4955-8c6f-ac2565b93fb0.png)

**Comment by drasticdpk** [comment]
@Amir-Khanal please go ahead. We need this feature by Jestha 10 for our bridge course.

**Comment by subhamsursa** [comment]
@suresmaharjan-sursatech what is the status for this ticket, can you update the estimate time for this please

**Comment by Amir-Khanal** [comment]
@drasticdpk sir, We will not be including the payment module for this time development; because this might take a longer time for development. Can you Please, confirm about this?

**Comment by drasticdpk** [comment]
yes please exclude the payment module for now.

**Comment by subhamsursa** [comment]
> yes please exclude the payment module for now.

@suresmaharjan-sursatech payment is out of scope for now

**Comment by Rashi011** [comment]
**Requirement changed**

1. We will be developing it in house 
2. We will be developing our own CMS

Note: We do not need a design for MCQ but a wireframe is needed. 

@phuyalrn22 will be working on frontend and @bipulmgr sir on backend 
cc: @subhamsursa @sursaone

**Comment by Rashi011** [comment]
**For admino**

1. For each question set need to assign a teacher through email/phone number

**Comment by alinac7** [comment]
Link to the prototype:

**Comment by alinac7** [comment]
Mobile Responsive Prototype Link: https://www.figma.com/proto/yoeFGwB3LsOZDi545yCgbM/Vurilo-Web?page-id=0%3A1&node-id=2971%3A14872&viewport=-15724%2C294%2C0.3&scaling=min-zoom&starting-point-node-id=2971%3A14872&show-proto-sidebar=1
