### ISSUE TITLE
[Live Session] - Requirement Update

### ISSUE THREAD

**Issue by phuyalrn22** [vurilo/roadmap#42]
Add multiple teams on creating live session if some team is free and other are paid.
Edit live session. single event and multiple event.

**Comment by Rashi011** [comment]
We will take this to another sprint

**Comment by Rashi011** [comment]
**Permission to edit live session before live event starts**
1. Event Title
2. User Limits
3. Event Description 
4. Live Session Thumbnail

**Comment by Rashi011** [comment]
The solution for "Add multiple teams on creating live session if some team is free and other are paid."
Need to check the role of the author of the live session before displaying "Teams" in the drop down. If the role is teacher or admin to the team, only then the team list should be displayed in the dropdown.
