### ISSUE TITLE
[Mobile Web] [Web] Dashboard

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#43]
### After Log in View

**Both Mobile and Web**

![Image from iOS (10)](https://user-images.githubusercontent.com/87527341/163113705-58806a9a-dbb8-416a-9811-5264fc4d21b0.jpg)

**Comment by Rashi011** [comment]
Ui design to be recreated.

**Comment by alinac7** [comment]
### Responsive Dashboard Design for both Mobile & Web 
- Screenshot of 1st Demo of Dashboard in both Mobile & Web
![image](https://user-images.githubusercontent.com/96462002/166442855-2122991b-b8fa-4438-8b12-fa3e08c8f66a.png)

- Link to Design File: 
https://www.figma.com/file/yaHp8I7fI0krT0OFjsPO1W/Vurilo-2.0-UI-Design?node-id=0%3A1

Please review @sursaone sir.

**Comment by sursaone** [comment]
Feedback provided
1. Need to do research on UX in the layout
2. After the UX of the layout is finalized, research different variations of colors to play with the layout
3. Finalized the layout
4. Create and follow the design system for vurilo
5. Based on the design system, we will keep improving the UX for inner content as a continuation process.

@Rashi011 @subhamsursa @alinac7
