### ISSUE TITLE
Admin Panel - Enhancement

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#45]
**To Do**

1. Live session review
2. Assessment review
3. Course review
4. Team size configuration

**Comment by Rashi011** [comment]
**Backend task for sprint 16**

1. Payment Details
2. Team Size API
3. Team List API

**Frontend task for sprint 16**

1. Design UI
2. Categories , Sub-Categories
3. Team List 
4. Team Size

**Comment by alinac7** [comment]
Link to the prototype: https://www.figma.com/proto/R4q43GKYpC2jhayExCu7Oy/Admino-Vurilo?page-id=0%3A1&node-id=9%3A3&viewport=241%2C48%2C0.17&scaling=min-zoom&starting-point-node-id=9%3A3

**Comment by Rashi011** [comment]
https://github.com/vurilo/stend/issues/1205
