### ISSUE TITLE
[Mobile App] : Teacher's View 

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#49]

**Comment by subhamsursa** [comment]
Need more details on this ticket for the development.

**Comment by subhamsursa** [comment]
@Rashi011 what is the status for this ticket ?

**Comment by Rashi011** [comment]
Holding this ticket, for now, I will start working on this ticket once the dashboard design is finalized @subhamsursa

**Comment by subhamsursa** [comment]
@Rashi011 how is the progress on design for this ticket ..

**Comment by Rashi011** [comment]
We are almost done working on UX of Teachers's view/mode
@alinac7 can you please share the link here?
