### ISSUE TITLE
[Mobile App] : Assignment Feature

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#51]
### Assignment 
**User(Assignment Author): Dashboard**

1. Users should be able to view the assignment list along with the related course's name on the assignment card
2. If user is the author of the assignment/course a label is required 

**Enrolled User**

1. Enrolled users should be able to view all the assignments in enrolled courses
2. Enrolled users should be able to submit assignments before the due date or extended date
3. Enrolled users should be able to view the review and score of the assignment given by teachers

**Assignment card**

1. “My Assignment” button should be inside the hamburger menu on the homepage
2. On clicking the assignment menu, Users should be able to view the assignment list(assignment card) which includes,

- assignment title 
- related course name in the assignment card
- due date

**Comment by subhamsursa** [comment]
Need design and Acceptance criteria to pick this ticket for development

**Comment by Rashi011** [comment]
@alinac7, please read the requirement once
let me know if any confusion

**Comment by alinac7** [comment]
Screenshots of UI Designs 

1. Assignment from Home Page
- The user can be able to view assignments from the home page.
![image](https://user-images.githubusercontent.com/96462002/165802161-26ffe29b-ead1-44c4-821f-d19f311645c0.png)

2. Assignment List Page 
- The user can be able to view all the assignment lists by clicking on see all. 
![image](https://user-images.githubusercontent.com/96462002/165802763-59c066ba-6021-45fa-96dd-07fbe604a0ec.png)

- The user can also view all the assignment lists from the "My Assignment" on the navigation drawer page.
![image](https://user-images.githubusercontent.com/96462002/165803553-435317aa-f70c-4515-9122-4d16c1e4c131.png)

3. While clicking on any assignments, the user will be redirected to the assignment detail page where he/she can be able to submit the files regarding assignments. 
![image](https://user-images.githubusercontent.com/96462002/165803324-0ae52c0a-7e2c-4f72-8fdc-dce5cd44548a.png)

**Comment by alinac7** [comment]
### Overall Updated Assignments UI Design (Reviewed and approved by @sursaone sir)
![image](https://user-images.githubusercontent.com/96462002/166206067-fe80c66f-68e8-4b5b-a857-6656dc60ea5d.png)

- Link to Figma Design File:
https://www.figma.com/file/OHXUA8u6VFD7sf7pXUWHdY/Vurilo-Mobile-Designs?node-id=1013%3A3346

**Comment by sursaone** [comment]
@alinac7 Added few comments on the assignement UI on figma.

**Comment by alinac7** [comment]
Made changes according to latest comments. 
![image](https://user-images.githubusercontent.com/96462002/166211230-bb60d8f5-ba54-4fd9-9df6-aba82e1b46b1.png)

**Comment by alinac7** [comment]
- Screenshot of Updated designs in submitting assignment
![image](https://user-images.githubusercontent.com/96462002/166976284-230cc331-2ec1-466d-b87f-3f3b56495a57.png)

- Link to design file: https://www.figma.com/file/OHXUA8u6VFD7sf7pXUWHdY/Vurilo-Mobile-Designs?node-id=1013%3A3346

**Comment by Rashi011** [comment]
We will pick this ticket, either in sprint 21 or sprint 22 @dbal620 @phuyalrn22 
Please go through this ticket
