### ISSUE TITLE
Training Assessment 

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#52]
to be discussed...

**Comment by subhamsursa** [comment]
@Amir-Khanal @Rashi011 @alinac7 please discuss this with business and share the complete requirement under this ticket. 

cc: @deepaksursa @binodsth

**Comment by subhamsursa** [comment]
@Rashi011 why this ticket is closed ??

**Comment by Rashi011** [comment]
Closed mistakenly
Was supposed to close https://github.com/vurilo/roadmap/issues/59 
@subhamsursa
