### ISSUE TITLE
Video Upload Services with background Jobs

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#54]

**Comment by Rashi011** [comment]
https://github.com/vurilo/stend/issues/934 - TASK
https://github.com/vurilo/stend/issues/928 - BUG

**Comment by subhamsursa** [comment]
@iambijay12 what is the status for this ticket ?

**Comment by Rashi011** [comment]
https://github.com/vurilo/stend/issues/1550

**Comment by Amir-Khanal** [comment]
currently raw videos as uploaded and displayed automatically and video conversion is done in the background.
