### ISSUE TITLE
[Teams Depth Enhancement] - the node depth should be till nth

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#56]
Currently n=4 
Need to enhance nth node depth of Teams/sub-teams

**Comment by subhamsursa** [comment]
Need more clear requirement from business, Dev team and Business should have grooming session for the implementation of this ticket. 
cc: @Rashi011 @iambijay12 @phuyalrn22 @alinac7 .

**Comment by subhamsursa** [comment]
closing this ticket
