### ISSUE TITLE
[Help Guide] -  tawk and docs

### ISSUE THREAD

**Issue by Rashi011** [vurilo/roadmap#78]
https://vuriloapp.tawk.help/ 

1. How to join Live Session 
2. How to record video
3. How to assign a "Co-host" to the user
4. How to mute or unmute users
5. How to enable/disable the chat function

Due date : 8/23/2022

**Comment by ST-Saurabh** [comment]
https://vuriloapp.tawk.help/category/teacher
https://drive.google.com/drive/folders/1lG2v28Bc-bdD13SKd9miejE9M2pt0MPV
