### ISSUE TITLE
Search bar need to be implemented in the sub team

### ISSUE THREAD

**Issue by ST-Saurabh** [vurilo/roadmap#83]
### Description
User should be able to search sub team members.

CC: @Amir-Khanal @Rashi011

**Comment by Amir-Khanal** [comment]
Yes also need to implement to display all the students phone number if loggged in and added to team using a phone number

**Comment by Rashi011** [comment]
Ref:

![image](https://user-images.githubusercontent.com/87527341/188568464-b62e7f05-fd10-4659-9e1f-dadb55101592.png)

**Comment by Rashi011** [comment]
This task has been completed
