### ISSUE TITLE
Description place Should support LaTeX/KaTeX

### ISSUE THREAD

**Issue by ST-Saurabh** [vurilo/roadmap#85]
### **Example:**
$$ 
A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}
$$
**Result**
![image](https://user-images.githubusercontent.com/109574221/188586690-21cadfd5-de5d-49d8-a47e-5515540ceb24.png)

### Refrences
- https://chemistry.meta.stackexchange.com/questions/86/faq-how-can-i-format-math-chemistry-expressions-on-chemistry-stack-exchange
- https://en.wikibooks.org/wiki/LaTeX/Mathematics
- https://en.wikibooks.org/wiki/LaTeX/Advanced_Mathematics

**Comment by sursaone** [comment]
done with some enhancements left
