### ISSUE TITLE
Option to make the recorded video unavailable for the student

### ISSUE THREAD

**Issue by ST-Saurabh** [vurilo/roadmap#96]
problem statement:
The student gets enroll in one of the online class. He will be able to view the recorded class so he will not take any extra class.
if the student fails then also he will not enroll in another session because he will get access to the recorded video.

The live session status also needs to be changed (active/inactive)

**Comment by Amir-Khanal** [comment]
1. LIVE SESSION Create Page
- Display "Do you want the Recording?" radio button with option Yes/No
- If Yes, Then Recordings availability should be decided with radio button; date+time picker and forever
- NO need to display extra course related details

### Recorded Course will be of different status i.e. Recordings

![image](https://user-images.githubusercontent.com/98070324/203488994-aec7b773-9abe-4576-bdb9-0bc47c5071e5.png)


2. Recordings Availability can be changed from Course 

![image](https://user-images.githubusercontent.com/98070324/203493202-f6a7943b-7b59-4418-9578-0108c5ea3b3c.png)

Who can access this Recording Course?
- LiveSession enrolled user (on Default)
- Can be made accessible to the Public and Teams as well

3. Sections and Lessons needs to updatable; in spite of publish status
4. the Recordings course needs to be published automatically
